## SPDX-License-Identifier: MIT
##
## Dynamic Color Palette v{version}
## Utility class for Godot 4
## (C) 2026 Frank Winter
## https://fwdotcom.itch.io/dynamic-color-palette
##
## This utility class is licensed under the MIT License for compatibility with Godot projects.
## See LICENSE file for full license text.
##
## This file was auto-generated by the DCP Blender addon on palette export.
## Do not edit manually — regenerate via the DCP panel in Blender.

class_name DCPUtil
extends RefCounted

## Filename of the exported albedo (color) texture.
const ALBEDO_IMAGE_NAME: String = "{albedo_image_name}"

## Filename of the exported material (PBR data) texture.
const MATERIAL_IMAGE_NAME: String = "{material_image_name}"

## Number of color columns in the palette.
const COLOR_COLUMNS: int = {color_columns}

## Number of color rows in the palette.
const COLOR_ROWS: int = {color_rows}

## Size of one palette cell in pixels.
const CELL_SIZE: int = {cell_size}

## Global emission multiplier baked into the shader node tree.
const EMISSION_FACTOR: float = {emission_factor}

## Emission strip strengths; one entry per strip, up to five.
const EMISSION_STRIPS: Array[float] = {emission_strips}

## Project info lines as set in the DCP panel.
const INFO_LINE1: String = "{info_line1}"
const INFO_LINE2: String = "{info_line2}"
const INFO_LINE3: String = "{info_line3}"
